INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Phone', 1200, 15);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Headset', 150, 40);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Laptop', 3500, 8);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Keyboard', 300, 25);
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY) VALUES ('Monitor', 1800, 12);